# Generated by Django 4.2 on 2023-06-01 19:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_unit', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('national_id', models.CharField(blank=True, max_length=14, null=True)),
                ('military_number', models.CharField(blank=True, max_length=13, null=True)),
                ('level', models.CharField(choices=[('admin', 'admin'), ('soldier', 'جندى'), ('arrif', 'عريف'), ('raqib', 'رقيب'), ('raqiba', 'رقيب اول'), ('mosaid', 'مساعد'), ('mosaida', 'مساعد اول'), ('molazim', 'ملازم'), ('molazima', 'ملازم أول'), ('naqib', 'نقيب'), ('raid', 'رائد'), ('moqadim', 'مقدم'), ('aqid', 'عقيد'), ('amid', 'عميد'), ('lwaa', 'لواء')], default='soldier', max_length=50)),
                ('date_added', models.DateField(blank=True, default=datetime.datetime(2023, 6, 1, 19, 5, 23, 363743, tzinfo=datetime.timezone.utc), null=True, verbose_name=' تاريخ الانضمام')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name=' تاريخ التسريح')),
                ('branch', models.CharField(choices=[('secrtary', 'السكرتارية'), ('nozom', 'نظم'), ('intag', 'انتاج'), ('tasleeh', 'تسليح'), ('tafteesh', ' تفتيش'), ('amn', 'امن'), ('maly', ' مالى'), ('tanzimafrad', 'تنظيم وافراد'), ('shdobat', ' شئون ضباط'), ('takhtit', 'تخطيط'), ('hamla', 'حملة'), ('ishara', 'اشارة'), ('kadaa', 'قضاء'), ('motabaa', 'متابعة'), ('tadreeb', 'تدريب')], default='secrtary', max_length=100)),
                ('redif_detection', models.CharField(blank=True, max_length=5, null=True)),
                ('main_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maindata.unit', verbose_name=' الحالة الصادر لها')),
            ],
        ),
    ]
