# Generated by Django 4.2 on 2023-06-01 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0002_alter_person_date_added_alter_person_main_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '  فرد', 'verbose_name_plural': ' الافراد'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': ' وحده اساسية', 'verbose_name_plural': 'الوحدات الاساسية'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='redif_detection',
        ),
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.CharField(choices=[('secrtary', 'السكرتارية'), ('nozom', 'نظم'), ('intag', 'انتاج'), ('tasleeh', 'تسليح'), ('tafteesh', ' تفتيش'), ('amn', 'امن'), ('maly', ' مالى'), ('tanzimafrad', 'تنظيم وافراد'), ('shdobat', ' شئون ضباط'), ('takhtit', 'تخطيط'), ('hamla', 'حملة'), ('ishara', 'اشارة'), ('kadaa', 'قضاء'), ('motabaa', 'متابعة'), ('tadreeb', 'تدريب')], default='secrtary', max_length=100, verbose_name='  الفرع'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 1, 22, 35, 7, 524256, tzinfo=datetime.timezone.utc), null=True, verbose_name=' تاريخ الانضمام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='level',
            field=models.CharField(choices=[('soldier', 'جندى'), ('arrif', 'عريف'), ('raqib', 'رقيب'), ('raqiba', 'رقيب اول'), ('mosaid', 'مساعد'), ('mosaida', 'مساعد اول'), ('molazim', 'ملازم'), ('molazima', 'ملازم أول'), ('naqib', 'نقيب'), ('raid', 'رائد'), ('moqadim', 'مقدم'), ('aqid', 'عقيد'), ('amid', 'عميد'), ('lwaa', 'لواء')], default='soldier', max_length=50, verbose_name=' الرتبة او الدرجة'),
        ),
        migrations.AlterField(
            model_name='person',
            name='military_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name=' الرقم العسكرى'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' الاسم'),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name=' الرقم القومى'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='main_unit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الوحدة الاساسية'),
        ),
    ]
