# Generated by Django 4.2 on 2023-06-02 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0004_alter_person_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='main_unit',
            new_name='mainunit',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='main_unit',
            new_name='mainunit',
        ),
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 2, 9, 15, 46, 787076, tzinfo=datetime.timezone.utc), null=True, verbose_name=' تاريخ الانضمام'),
        ),
    ]
