# Generated by Django 4.2 on 2023-06-14 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0006_alter_person_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 14, 18, 53, 59, 151800, tzinfo=datetime.timezone.utc), null=True, verbose_name=' تاريخ الانضمام'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='mainunit',
            field=models.CharField(default='', max_length=200, verbose_name='الوحدة الاساسية'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hliday_type', models.CharField(choices=[('leave', 'اجازة معتادة'), ('rest', 'راحة'), ('emerg', 'عارضة'), ('crest', 'بدل راحة'), ('yearly', 'سنوية'), ('mission', ' مأمورية'), ('training', 'دورة')], default='leave', max_length=100, verbose_name='نوع الاجازة')),
                ('date_from', models.DateField(blank=True, default=datetime.datetime(2023, 6, 14, 18, 53, 59, 151800, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ الذهاب')),
                ('date_to', models.DateField(blank=True, default=datetime.datetime(2023, 6, 21, 18, 53, 59, 151800, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ العوده')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maindata.person', verbose_name='الفرد')),
            ],
            options={
                'verbose_name': '  اجازة',
                'verbose_name_plural': ' الاجازات',
            },
        ),
    ]
