# Generated by Django 4.2 on 2023-07-05 04:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0007_alter_person_date_added_alter_unit_mainunit_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='فرع او مكتب')),
            ],
            options={
                'verbose_name': 'فرع او مكتب',
                'verbose_name_plural': 'الفروع',
            },
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 5, 4, 41, 50, 819740, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ الذهاب'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 12, 4, 41, 50, 819740, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ العوده'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='hliday_type',
            field=models.CharField(choices=[('leave', 'اجازة معتادة'), ('civil', ' مدنية'), ('rest', 'راحة'), ('emerg', 'عارضة'), ('crest', 'بدل راحة'), ('yearly', 'سنوية'), ('mission', ' مأمورية'), ('training', 'دورة')], default='leave', max_length=100, verbose_name='نوع الاجازة'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 5, 4, 41, 50, 819740, tzinfo=datetime.timezone.utc), null=True, verbose_name=' تاريخ الانضمام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mainunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maindata.unit', verbose_name=' الوحدة الاساسية'),
        ),
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.branch', verbose_name=' الفرع'),
        ),
    ]
