# Generated by Django 4.2 on 2023-07-08 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0008_branch_alter_holiday_date_from_alter_holiday_date_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidaytype', models.CharField(max_length=50, verbose_name='  نوع اجازة')),
            ],
            options={
                'verbose_name': ' نوع اجازة',
                'verbose_name_plural': 'نوع الاجازة',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, verbose_name=' درجة او رتبة ')),
            ],
            options={
                'verbose_name': 'درجة او رتبة',
                'verbose_name_plural': 'الدرجة او الرتبة',
            },
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='hliday_type',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 8, 16, 58, 13, 294387, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ الذهاب'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 15, 16, 58, 13, 294387, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ العوده'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 8, 16, 58, 13, 294387, tzinfo=datetime.timezone.utc), null=True, verbose_name=' تاريخ الانضمام'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='holidaytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maindata.holidaytype', verbose_name='  نوع الاجازة '),
        ),
        migrations.AlterField(
            model_name='person',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maindata.level', verbose_name=' الرتبة او الدرجة'),
        ),
    ]
