# Generated by Django 4.1.3 on 2023-06-13 09:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0008_alter_person_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 13, 9, 46, 15, 152435, tzinfo=datetime.timezone.utc), null=True, verbose_name=' تاريخ الانضمام'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hliday_type', models.CharField(choices=[('leave', 'اجازة معتادة'), ('rest', 'راحة'), ('emerg', 'عارضة'), ('crest', 'بدل راحة'), ('yearly', 'سنوية'), ('mission', ' مأمورية'), ('training', 'دورة')], default='secrtary', max_length=100, verbose_name='نوع الاجازة')),
                ('date_from', models.DateField(blank=True, default=datetime.datetime(2023, 6, 13, 9, 46, 15, 152435, tzinfo=datetime.timezone.utc), null=True, verbose_name='من')),
                ('date_to', models.DateField(blank=True, default=datetime.datetime(2023, 6, 20, 9, 46, 15, 152435, tzinfo=datetime.timezone.utc), null=True, verbose_name='من')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maindata.person', verbose_name='الفرد')),
            ],
            options={
                'verbose_name': '  اجازة',
                'verbose_name_plural': ' الاجازات',
            },
        ),
    ]
