# Generated by Django 4.1.3 on 2023-06-13 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0009_alter_person_date_added_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 13, 11, 11, 40, 124741, tzinfo=datetime.timezone.utc), null=True, verbose_name='من'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 20, 11, 11, 40, 124741, tzinfo=datetime.timezone.utc), null=True, verbose_name='من'),
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='person',
        ),
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 13, 11, 11, 40, 124741, tzinfo=datetime.timezone.utc), null=True, verbose_name=' تاريخ الانضمام'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='person',
            field=models.ManyToManyField(to='maindata.person', verbose_name='الفرد'),
        ),
    ]
