# Generated by Django 4.2 on 2023-07-08 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0009_holidaytype_level_remove_holiday_hliday_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 8, 17, 2, 52, 805479, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ الذهاب'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 15, 17, 2, 52, 805479, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ العوده'),
        ),
        migrations.AlterField(
            model_name='holidaytype',
            name='holidaytype',
            field=models.CharField(max_length=100, verbose_name='  نوع اجازة'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=100, verbose_name=' درجة او رتبة '),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 8, 17, 2, 52, 805479, tzinfo=datetime.timezone.utc), null=True, verbose_name=' تاريخ الانضمام'),
        ),
    ]
